=== speedydelete/3body/src/lang/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "https://raw.githubusercontent.com/speedydelete/3body/refs/heads/main/src/lang/schema.json",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "name": {
            "type": "string",
            "value": "The name of the language"
        },
        "title": {
            "type": "string",
            "description": "The HTML title element's value"
        },
        "elements": {
            "type": "array",
            "description": "Chemical elements",
            "minItems": 119,
            "maxItems": 119,
            "items": {
                "type": "string"
            }
        },
        "specialIsotopeNames": {
            "type": "object",
            "description": "Special names for isotopes (e.g. deuterium)",
            "patternProperties": {
                "^\\d+,\\d+$": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "molecules": {
            "type": "object",
            "description": "Names of molecules",
            "additionalProperties": {
                "type": "string"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "name",
        "title",
        "elements",
        "molecules"
    ]
}

=== speedydelete/3body/src/lang/en.json
{
    "$schema": "./schema.json",
    "name": "English",
    "title": "Three Body",
    "elements": [
        "Neutronium",
        "Hydrogen",
        "Helium",
        "Lithium",
        "Beryllium",
        "Boron",
        "Carbon",
        "Nitrogen",
        "Oxygen",
        "Flourine",
        "Neon",
        "Sodium",
        "Magnesium",
        "Aluminum",
        "Silicon",
        "Phosphorus",
        "Sulfur",
        "Chlorine",
        "Argon",
        "Potassium",
        "Calcium",
        "Scandium",
        "Titanium",
        "Vanadium",
        "Chromium",
        "Manganese",
        "Iron",
        "Cobalt",
        "Nickel",
        "Copper",
        "Zinc",
        "Gallium",
        "Germanium",
        "Arsenic",
        "Selenium",
        "Bromine",
        "Krypton",
        "Rubidium",
        "Strontium",
        "Yttrium",
        "Zirconium",
        "Niobium",
        "Molybdeneum",
        "Technetium",
        "Ruthenium",
        "Rhodium",
        "Palladium",
        "Silver",
        "Cadmium",
        "Indium",
        "Tin",
        "Antimony",
        "Tellurium",
        "Iodine",
        "Xenon",
        "Cesium",
        "Barium",
        "Lanthanum",
        "Cerium",
        "Praesodymium",
        "Neodymium",
        "Promethium",
        "Samarium",
        "Europium",
        "Gadolinium",
        "Terbium",
        "Dysprosium",
        "Holmium",
        "Erbium",
        "Thulium",
        "Ytterbium",
        "Lutetium",
        "Hafnium",
        "Tantalum",
        "Tungsten",
        "Rhenium",
        "Osmium",
        "Iridium",
        "Platinum",
        "Gold",
        "Mercury",
        "Thallium",
        "Lead",
        "Bismuth",
        "Polonium",
        "Astastine",
        "Radon",
        "Francium",
        "Radium",
        "Actinium",
        "Thorium",
        "Protactinium",
        "Uranium",
        "Neptunium",
        "Plutonium",
        "Americium",
        "Curium",
        "Berkelium",
        "Californium",
        "Einsteinium",
        "Fermium",
        "Mendelevium",
        "Nobelium",
        "Lawrencium",
        "Rutherfordium",
        "Dubnium",
        "Seaborgium",
        "Bohrium",
        "Hassium",
        "Meitnerium",
        "Darmstadtium",
        "Roentgenium",
        "Copernicium",
        "Nihonium",
        "Flerovium",
        "Moscovium",
        "Livermorium",
        "Tennessine",
        "Oganesson"
    ],
    "specialIsotopeNames": {
        "1,2": "Deuterium",
        "1,3": "Tritium"
    },
    "molecules": {
        "hydrogen": "Hydrogen",
        "helium": "Helium",
        "lithium": "Lithium",
        "beryllium": "Beryllium",
        "boron": "Boron",
        "carbon": "Carbon",
        "nitrogen": "Nitrogen",
        "oxygen": "Oxygen",
        "flourine": "Flourine",
        "neon": "Neon",
        "sodium": "Sodium",
        "magnesium": "Magnesium",
        "aluminum": "Aluminum",
        "silicon": "Silicon",
        "phosphorus": "Phosphorus",
        "sulfur": "Sulfur",
        "chlorine": "Chlorine",
        "argon": "Argon",
        "potassium": "Potassium",
        "calcium": "Calcium",
        "scandium": "Scandium",
        "titanium": "Titanium",
        "vanadium": "Vanadium",
        "chromium": "Chromium",
        "manganese": "Manganese",
        "iron": "Iron",
        "cobalt": "Cobalt",
        "nickel": "Nickel",
        "copper": "Copper",
        "zinc": "Zinc",
        "gallium": "Gallium",
        "germanium": "Germanium",
        "arsenic": "Arsenic",
        "selenium": "Selenium",
        "bromine": "Bromine",
        "krypton": "Krypton",
        "rubidium": "Rubidium",
        "Strontium": "Strontium",
        "yttrium": "Yttrium",
        "zirconium": "Zirconium",
        "niobium": "Niobium",
        "molybdeneum": "Molybdeneum",
        "technetium": "Technetium",
        "ruthenium": "Ruthenium",
        "rhodium": "Rhodium",
        "palladium": "Palladium",
        "silver": "Silver",
        "cadmium": "Cadmium",
        "indium": "Indium",
        "tin": "Tin",
        "antimony": "Antimony",
        "tellurium": "Tellurium",
        "iodine": "Iodine",
        "xenon": "Xenon",
        "cesium": "Cesium",
        "barium": "Barium",
        "lanthanum": "Lanthanum",
        "cerium": "Cerium",
        "praesodymium": "Praesodymium",
        "neodymium": "Neodymium",
        "promethium": "Promethium",
        "samarium": "Samarium",
        "europium": "Europium",
        "gadolinium": "Gadolinium",
        "terbium": "Terbium",
        "dysprosium": "Dysprosium",
        "holmium": "Holmium",
        "erbium": "Erbium",
        "thulium": "Thulium",
        "ytterbium": "Ytterbium",
        "lutetium": "Lutetium",
        "hafnium": "Hafnium",
        "tantalum": "Tantalum",
        "tungsten": "Tungsten",
        "rhenium": "Rhenium",
        "osmium": "Osmium",
        "iridium": "Iridium",
        "platinum": "Platinum",
        "gold": "Gold",
        "mercury": "Mercury",
        "thallium": "Thallium",
        "lead": "Lead",
        "bismuth": "Bismuth",
        "polonium": "Polonium",
        "astastine": "Astastine",
        "radon": "Radon",
        "francium": "Francium",
        "radium": "Radium",
        "actinium": "Actinium",
        "thorium": "Thorium",
        "protactinium": "Protactinium",
        "uranium": "Uranium",
        "neptunium": "Neptunium",
        "plutonium": "Plutonium",
        "americium": "Americium",
        "curium": "Curium",
        "berkelium": "Berkelium",
        "californium": "Californium",
        "einsteinium": "Einsteinium",
        "fermium": "Fermium",
        "mendelevium": "Mendelevium",
        "nobelium": "Nobelium",
        "lawrencium": "Lawrencium",
        "rutherfordium": "Rutherfordium",
        "dubnium": "Dubnium",
        "seaborgium": "Seaborgium",
        "bohrium": "Bohrium",
        "hassium": "Hassium",
        "meitnerium": "Meitnerium",
        "darmstadtium": "Darmstadtium",
        "roentgenium": "Roentgenium",
        "copernicium": "Copernicium",
        "nihonium": "Nihonium",
        "flerovium": "Flerovium",
        "moscovium": "Moscovium",
        "livermorium": "Livermorium",
        "tennessine": "Tennessine",
        "oganesson": "Oganesson",
        "water": "Water"
    }
}
